# SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 BombasterDS <115770678+BombasterDS@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: startingGear
  id: ChronoLegionnaireGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad # KS14 - Added this <
    back: ClothingBackpackStasisBatteryUnremoveableFilled
    mask: ClothingMaskGasChronoUnremoveable
    eyes: ClothingEyesGlassesUltra # KS14 - Added this <
    ears: ClothingHeadsetChronolegioneerUnremoveable
    gloves: ClothingHandsGlovesUltra # KS14 - Added this <
    outerClothing: ClothingOuterHardsuitChronolegioneerUnremoveable
    suitstorage: JetpackChrono # KS14 - Added this <
    shoes: ClothingShoesBootsChronoUnremoveable
    id: ChronoPDA
    belt: WeaponStasisGun
    pocket1: PinpointerStation
    pocket2: SonicScrewdriver
  special: # KS14 - Added autoimplant
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, NutrimentPumpImplant, StypticStimulatorImplant ]
